### ISSUE TITLE
Wrong HL Version recommendations for Betas newer than 6.1

### ISSUE THREAD

**Issue by Half-Modern** [Ch0wW/counterstrike-betas#3]
Counter-Strike Beta 6.1 was the last version which used the old-netcode version of HL Engine (1.0.1.6).
Starting with Beta 6.5, Counter-Strike began using the new-netcode engine (1.1.0.0 and onwards), which requires using 1.1.0.0 or newer (even the current Steam version can run it) version of Half-Life engine.

So these versions must have 1.1.1.0 instead of 1.0.1.6 as **recommended engine version**:

-Beta 6.5
-Beta 6.6
-Beta 7.0
-Beta 7.1

**Comment by Ch0wW** [comment]
I applied the changes, as well as adding a small addentum regarding CSB 6.5 and Steam! Thank you very much!
